### Numpy

#### ¿Qué vas a aprender en este curso?

Aprenderas a manejar y analizar grandes volúmenes de datos de forma eficiente utilizando 3 herramientas fundamentales en Python:

- NumPy: Te permite realizar operaciones matemáticas y estadísticas de alto rendimiento.
- Pandas: Facilita la manipulación de datos de forma rápida y sencilla. Ideal para trabajar con datos tabulares como los que se encuentras en hojas de cálculo o bases de datos.
- Matplotlib: Te permite visualizar datos de forma efectiva.

In [1]:
import numpy as np


### Dimensiones

los escalares tienen dimension 0
los vectores 1 dimension
las matrices 2 dimensiones
Todos son tensores. Los tensores de 2D son las matrices, de 1D los vectores y 0D los escalares.

In [2]:
escalar = np.array(42)
print(escalar)
print(type(escalar))

42
<class 'numpy.ndarray'>


In [3]:
vector = np.array([29, 30, 33, 31,32,35,42])
print(vector)

[29 30 33 31 32 35 42]


In [4]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [6]:
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
eye_matrix = np.eye(5)
print(eye_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
diag = np.diag([1,2,3,4,5])
print(diag)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [11]:
random = np.random.random((2,3))  # 2 filas y 3 columnas
print(random)

[[0.80266827 0.04774039 0.27332655]
 [0.45186939 0.90824528 0.61257522]]


### Existen 6 mecanismos generales para crear Arrays:

1. Conversión desde otras estructuras de Python (por ejemplo, listas y tuplas)
2. Funciones intrínsecas de NumPy para la creación de arrays (por ejemplo, arange, ones, zeros, etc.)
3. Replicación, unión o mutación de matrices existentes
4. Lectura de matrices desde disco, ya sea desde formatos estándar o personalizados
5. Creación de matrices a partir de bytes sin procesar mediante cadenas o buffers.
6. Utilización de funciones especiales de biblioteca (por ejemplo, random)
