In [1]:
import numpy as np

### Arrays y listas

Las listas pueden tener cualquier dato, los arrays tienen datos con tipos homogeneos.

| Característica	| Listas de Python	| Arrays de NumPy |
|---|---|---|
| Tipo de datos	| Puede contener diferentes tipos	| Todos los elementos deben ser del mismo tipo |
| Tamaño |	Dinámico |	Fijo en la creación |
| Eficiencia en cálculos| 	Menor |	Mayor |
| Funciones matemáticas |	Limitadas |	Amplia gama de funciones |
| Consumo de memoria |	Mayor |	Menor |

In [5]:
array1 = np.array([[1, 2, 3],[ 4, 5, 6]])
print(array1.ndim)
print(array1.shape)
print(array1.dtype)
print(array1)

2
(2, 3)
int64
[[1 2 3]
 [4 5 6]]


### Tipos de datos
| Tipo | detalle | rango |
|---|---|---|
| uint8 | entero sin signo | 0 a 255 |
| float32 | numero de punto flotante de rango moderado | 1.175494351e-38 a 3.402823466e+38 |
| float64 | numero de punto flotante de doble precision | 2.2250738585072014e-308 a 1.7976931348623157e+308 |



In [6]:
z = np.array(3, dtype='uint8')
print(z)
print(z.dtype)

3
uint8


In [7]:
double_array = np.array([[1, 2, 3],[ 4, 5, 6]], dtype='d')
print(double_array)
print(double_array.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
float64


In [8]:
z = z.astype('float32')
print(z)
print(z.dtype)

3.0
float32


In [9]:
array2 = np.array([[1, 2, 3],[ 4, 5, 6]])
sum = np.sum(array2)
print(sum)

21


In [11]:
array3 = np.array([[1, 2, 3],[ 4, 5, 6]])
mean = np.mean(array3)
print(mean)

3.5


In [12]:
array4 = np.array([[1, 2, 3],[ 4, 5, 6]])
std = np.std(array4)
print(std)

1.707825127659933
