In [6]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])
print(array[1])
print(array[-1])
print(array[-2])
print(array[1:4])
print(array[1:7])
print(array[-1:-7])


20
50
40
[20 30 40]
[20 30 40 50]
[]


In [9]:
bool_index = array > 30
print(bool_index)
print(array[bool_index])
print(array[array > 30])


[False False False  True  True]
[40 50]
[40 50]


In [10]:
index = [1,2,3]
print(array[index])

[20 30 40]


In [11]:
index = [2,0,4]
print(array[index])

[30 10 50]


In [22]:
array = np.random.randint(1,10, size=(3,3))
print(array)
print(array[0,1])
print(array[:2,:2])
print(array[:3,:3])
print(array[:1,:1])
print(array[1:2,1:2])

[[4 7 8]
 [7 2 8]
 [7 5 5]]
7
[[4 7]
 [7 2]]
[[4 7 8]
 [7 2 8]
 [7 5 5]]
[[4]]
[[2]]
