In [1]:
import numpy as np

In [3]:
prices = np.array([100, 200, 250, 150, 50])
discount = np.array([0.1])
discounted_prices = prices - prices * discount
print(discounted_prices)

[ 90. 180. 225. 135.  45.]


In [5]:
prices = np.random.randint(100, 500, size=(3, 3))
discount = np.array([10,20,30])
discounted_prices = prices - discount
print(prices    )
print(discounted_prices)

[[452 288 120]
 [142 305 341]
 [175 218 252]]
[[442 268  90]
 [132 285 311]
 [165 198 222]]


In [7]:
array = np.array([1, 2, 3, 4, 5])
print(np.all(array > 0))
print(np.all(array > 1))
print(np.any(array > 1))

True
False
True


In [8]:
array_a = np.array([1, 2, 3])
array_b = np.array([ 4, 5, 6])
concatenated = np.concatenate((array_a, array_b))
print(concatenated)

[1 2 3 4 5 6]


In [11]:
array_a = np.array([1, 2, 3])
array_b = np.array([ 4, 5, 6])
stacked = np.stack((array_a, array_b))
stackedv = np.vstack((array_a, array_b))
stackedh = np.hstack((array_a, array_b))
print(stacked)
print(stackedv)
print(stackedh)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [18]:
array_c = np.arange(1, 13)
split = np.split(array_c, 3)
print(array_c)
print(split)
print(split[0])
print(split[2])

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
[1 2 3 4]
[ 9 10 11 12]
