In [2]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
transponed = matrix.T
print(matrix)
print(transponed)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
array = np.arange(12)
reshaped_array = array.reshape(3, 4)
print(array)
print(reshaped_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
array = np.arange(12)
reversed_array = array[::-1]
print(array)
print(reversed_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[11 10  9  8  7  6  5  4  3  2  1  0]


In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flattened_matrix = matrix.flatten()
print(matrix)
print(flattened_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
