# Ejercicios en numpay

## Conexión entre NumPy, Pandas y Matplotlib
1. NumPy como Fundamento

    - NumPy es la base sobre la que se construyen muchas otras librerías de análisis de datos en Python, incluidas Pandas y Matplotlib.
    - Con NumPy, has aprendido a manejar arrays multidimensionales y realizar cálculos matemáticos y matriciales eficientes. Estos arrays son fundamentales porque Pandas y Matplotlib los utilizan bajo el capó para realizar muchas de sus operaciones.

2. Pandas para la Manipulación de Datos

    - Mientras que NumPy se especializa en operaciones numéricas y matriciales, Pandas es la herramienta que utilizarás para la manipulación de datos estructurados, como tablas y series temporales.
    - Pandas toma los arrays de NumPy y les da estructura en forma de DataFrames y Series, lo que facilita la limpieza, transformación y análisis de datos complejos.
    - Ejemplo de Conexión: Puedes usar NumPy para realizar cálculos en un conjunto de datos, luego importar esos resultados a un DataFrame de Pandas para un análisis más detallado.

3. Matplotlib para la Visualización de Datos

    - Matplotlib es la librería de referencia para la visualización de datos en Python. Te permitirá transformar tus datos en gráficos e imágenes que comunican claramente tus hallazgos.
    - Tanto NumPy como Pandas se integran perfectamente con Matplotlib, permitiéndote crear gráficos desde arrays de NumPy o directamente desde DataFrames de Pandas.
    - Ejemplo de Conexión: Después de procesar y analizar datos con NumPy y Pandas, puedes usar Matplotlib para crear gráficos que visualicen las tendencias, patrones y anomalías en los datos.

4. El Flujo de Trabajo Completo

    - Cargar y Manipular Datos: Utilizas Pandas para cargar y estructurar tus datos desde diversas fuentes (como CSVs, Excel, bases de datos).
    - Análisis Numérico y Cálculos: Usas NumPy para realizar cálculos intensivos, como operaciones matriciales y simulaciones.
    - Visualización de Resultados: Finalmente, Matplotlib te ayuda a visualizar los resultados de tus análisis, creando gráficos que pueden comunicarse efectivamente con tu audiencia.

## Ejercicios Prácticos con NumPy
Vamos a consolidar lo que has aprendido con ejercicios exclusivos de NumPy, diseñados para reforzar tus habilidades y prepararte para las conexiones futuras con Pandas y Matplotlib.

1. Operaciones Básicas con Arrays

    - Instrucción: Crea dos arrays de 1D con valores enteros y realiza las operaciones de suma, resta, multiplicación, y división entre ellos.

In [2]:
import numpy as np

array1 = np.array([10, 20, 30, 40])
array2 = np.array([1, 2, 3, 4])

suma = array1 + array2
resta = array1 - array2
multiplicacion = array1 * array2
division = array1 / array2
print('array1:', array1)
print('array2:', array2)
print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)

array1: [10 20 30 40]
array2: [1 2 3 4]
Suma: [11 22 33 44]
Resta: [ 9 18 27 36]
Multiplicación: [ 10  40  90 160]
División: [10. 10. 10. 10.]


2. Cálculos Estadísticos en Arrays

    - Instrucción: Dado un array de datos, calcula la media, mediana, varianza, y desviación estándar.

In [4]:
datos = np.array([23, 76, 35, 67, 89, 45, 68, 79, 35])

media = np.mean(datos).round(2)
mediana = np.median(datos).round(2)
varianza = np.var(datos).round(2)
desviacion = np.std(datos).round(2)

print("Media:", media)
print("Mediana:", mediana)
print("Varianza:", varianza)
print("Desviación estándar:", desviacion)

Media: 57.44
Mediana: 67.0
Varianza: 484.02
Desviación estándar: 22.0


3. Operaciones Matriciales

    - Instrucción: Crea dos matrices de 2x2 y realiza las operaciones de suma, resta, multiplicación (producto matricial) y cálculo de la inversa de una de ellas.

In [6]:
import numpy as np

matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

suma_matrices = matriz1 + matriz2
resta_matrices = matriz1 - matriz2
producto_matrices = np.dot(matriz1, matriz2)
inversa_matriz1 = np.linalg.inv(matriz1)
print("Matriz 1:\n", matriz1)
print("Matriz 2:\n", matriz2)
print("Suma de matrices:\n", suma_matrices)
print("Resta de matrices:\n", resta_matrices)
print("Producto de matrices:\n", producto_matrices)
print("Inversa de la matriz 1:\n", inversa_matriz1)

Matriz 1:
 [[1 2]
 [3 4]]
Matriz 2:
 [[5 6]
 [7 8]]
Suma de matrices:
 [[ 6  8]
 [10 12]]
Resta de matrices:
 [[-4 -4]
 [-4 -4]]
Producto de matrices:
 [[19 22]
 [43 50]]
Inversa de la matriz 1:
 [[-2.   1. ]
 [ 1.5 -0.5]]


4. Resolución de un Sistema de Ecuaciones Lineales

    - Instrucción: Resuelve el sistema de ecuaciones lineales dado por Ax=b, donde A es una matriz 2x2 y b es un vector de 2 elementos.
    Ax=bAx = b

In [8]:
A = np.array([[2, 3], [1, 2]])
b = np.array([8, 5])

x = np.linalg.solve(A, b)
print("Matriz A:\n", A)
print("Vector b:\n", b)
print("Solución del sistema de ecuaciones:", x)

Matriz A:
 [[2 3]
 [1 2]]
Vector b:
 [8 5]
Solución del sistema de ecuaciones: [1. 2.]


5. Simulación de Datos

    - Instrucción: Genera un array de 1000 números aleatorios que sigan una distribución normal con media 0 y desviación estándar 1. Calcula la media y desviación estándar del array generado.

In [9]:
datos_simulados = np.random.normal(0, 1, 1000)
media_simulada = np.mean(datos_simulados)
desviacion_simulada = np.std(datos_simulados)
print("Datos simulados:", datos_simulados)
print("Media de los datos simulados:", media_simulada)
print("Desviación estándar de los datos simulados:", desviacion_simulada)

Datos simulados: [ 0.87864301  0.23607861 -0.44832206 -0.56768524 -0.77148115  1.3142372
  0.47130087  0.50805479  1.07355821 -0.01116699  0.75338134 -0.97458246
  0.70129157  1.21368219  0.30577671 -0.71818563 -0.82598001  0.71380662
 -0.85244666  1.00793647 -2.10538338  0.46816183  0.73002415  1.48165162
  0.53161469 -0.3896586  -1.36781162 -0.24842438 -0.69480802  0.73978364
 -0.08390645  1.02639572  0.24032476  1.70864515 -0.27890405 -0.55459775
  0.1637797  -1.58036217 -1.71507997  0.40560275 -0.43110757 -0.15849894
  0.71470396 -0.57340067  0.60745923  0.27846717  1.32955834  2.75766288
  1.03885229  1.18733553  0.26144641  0.09587598 -0.86422126  0.08889071
  1.12356398 -1.01491675  0.84289265  0.41730328 -1.18666671 -0.7441745
 -0.46076538  0.3182333  -0.55694087 -1.36097574 -0.57172292 -1.63583967
  0.28987884  0.75464111 -0.73476006 -0.0811822   0.08914343  0.04739568
 -0.52113375  1.1478579   1.56357014 -0.60406644 -0.21905946  1.16391453
  0.72409407  0.14470185  0.40176722